### ISSUE TITLE
Modules to clean up

### ISSUE THREAD

**Issue by aguinot** [CosmoStat/shapepipe#404]
Here is a list of what I think are the easiest and first module to clean up : 

- [x] SExtractor_runner / SExtractor_runner_exp (#412)
- [x] PSFEx_runner (#413)
- [x] vignetmaker_runner / vignetmaker_runner2 (#411)
- [x] split_exp_runner (#410)
- [x] core pipeline (#415)
- [x] make_catalog_runner (#435)
- [x] SETools (#430)
- [x] psfex_interp_runner (#434)
- [x] MCCD (#431)
- [x] find_exposures_runner (#423)
- [x] get_images_runner (#429)
- [x] uncompress_fits_image_runner (#427 )
- [x] spread_model_runner (#403)
