### ISSUE TITLE
[Management] Modules to Clean Up II

### ISSUE THREAD

**Issue by sfarrens** [CosmoStat/shapepipe#454]
Issues for [second code clean up milestone](https://github.com/CosmoStat/shapepipe/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Second+Code+Clean+Up%22)

## Modules

- [x] make_catalog (#460)
- [x] mask_runner / mask_runner_exp (#469)
- [x] match_external_runner (#464)
- [x] merge_headers_runner (#492)
- [x] merge_sep_cats_runner (#461)
- [x] merge_star_cat_runner (#467)
- [x] paste_cat_runner (#470)
- [x] ngmix_runner (#468)

## Pipeline

- [x] file_io (#477)

## Utilities

- [x] canfar (#455)
- [x] cfis (#458)
- [x] galaxy (#462)
- [x] file_system (#463)
