### ISSUE TITLE
[Management] Module Documentation

### ISSUE THREAD

**Issue by sfarrens** [CosmoStat/shapepipe#494]
Add module documentation according to #481 to the following modules.

> Edit this list to attach PRs corresponding to a given module

- [x] find_exposures #481, #487
- [x] get_images #481
- [x] make_cat #530
- [x] mask #505 
- [x] match_external #533
- [x] MCCD #528
- [x] merge_headers #497
- [x] merge_sep_cats #529 
- [x] merge_star_cat #532
- [x] ngmix #537
- [x] paste_cat #531
- [x] psfex_interp #526
- [x] psfex #535
- [x] random_cat #525
- [x] setools #510 
- [x] SExtractor #534
- [x] split_exp #496
- [x] spread_model #524
- [x] uncompress_fits_image #489
- [x] vignetmaker #523
